version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres
    volumes:
      - postgresdata:/var/lib/postgresql/data
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_USER=postgres
         - POSTGRES_DB=library
    restart: unless-stopped
  springbootapp:
    image: dlekhanov/spring-framework-17:0.0.1
    network_mode: bridge
    container_name: springbootapp
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_USER=postgres
         - DB_URL=jdbc:postgresql://localhost:5432/library
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
volumes:
  postgresdata: